name: Demo trigger events

on:
  # Webhook events
  push:
    branches:
      - main
      - feat/*
  pull_request:
      branches:
        - main
  issues:
    types:
      - opened
      - closed
  # Schedule events
  schedule:
    - cron: 0 0  * * *  
    - cron: 0 9 * * 0
  # Manual events
  workflow_dispatch:
    inputs:
      yourName:
        description: Your name
        required: true
        default: My Friend
      areYouFeelingGood:
        default: true
        required: true
        type: boolean
      howDoYouFindGithubActions:
        default: Github actions good?
        required: false
        type: choice
        options:
          - Awesome
          - Okay
          - Na
env:
  MY_NAME: Oezguer
  GREETING: Hello
jobs:
  Greeting:
    runs-on: ubuntu-latest
    env:
      GREETING: Good morning
    steps:
      - name: "Greeting step (expectation: Hello Oezguer)"
        run: echo $GREETING $MY_NAME
  Greeting2:
    runs-on: ubuntu-latest
    env:
      GREETING: Good morning
    steps:
      - name: "Greeting step (expectation: Good morning Oezguer)"
        run: echo $GREETING $MY_NAME
      - name: "Greeting step (expectation: Good afternoon Oezguer)"
        run: echo $GREETING $MY_NAME
        env:
          GREETING: Good afternoon
  Job2:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name: Step2
        run: echo "${{github.actor}} is learning Github actions."
      - name: Step 3
        run: echo "Great!"
        if: ${{inputs.areYouFeelingGood}}
      - name: Step4
        run: echo "No worries, I am here with you!"
        if: ${{inputs.areYouFeelingGood == false}}
