# create a workflow with a name of your choice
name: first workflow

# it should be triggered whenever there is a push on the main branch
on:
  push: 
    branches:
      - main
  workflow_dispatch: 
    inputs:
      myVar1:
        type: boolean
        default: false
        description: Please check
      myVar2:
        type: string
        description: Please add some text
# it should be triggered manually too

# define 2 environment variables:  VAR1 an VAR2
# VAR1 is boolean
# VAR2 is string
env:
  VAR1: ${{inputs.myVar1}}
  VAR2: ${{inputs.myVar2}}

# it should have 2 jobs
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 Job-1"
        run: echo ${{env.VAR2}}
        if: ${{env.VAR1 == "true"}}
      - name: "Step 2 Job-1"
        run: echo ${{github.actor}}
# 1st job should contains 2 steps
# step 1:
# - should be executed only if VAR1 is true
# - echo the VAR2
# - echo your name

# 2nd job should be executed only if job1 is executed successfully
# job2 has only 1 step - you can do here anything you want, e.g. echo "good morning"
# Commit the file and run the workflow, check everything works

  job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: "Job-2"
          run: echo "2nd job"
